### PR TITLE
Documentation Overhaul

### PR DESCRIPTION
**Pull request by joshrosso**
As I'm setting up for [episode 119](https://tgik.io/119), I'm overhauling the documentation to include detailed instructions.

My hope is this will act as a better on-ramp for future TGIK hosts.

[Full update can be viewed here.](https://github.com/vmware-tanzu/tgik/blob/daccdb53127200093a4ef8388433113d5e308a43/documentation/README.md)

### CODE REVIEW

**Comment by joshrosso** [comment]
Ready for review / potential merge.

**Comment by mauilion** [comment]
Looks awesome! Can you add the bit about associating the video with the tgik playlist at scheduling time. .

**Comment by joshrosso** [comment]
Great idea, on it!

**Comment by joshrosso** [comment]
@mauilion added

* YT Playlist
* Hackmd setup
* Wrapping up

**Comment by mauilion** [comment]
Thanks! Merged!

**Pull request merged**
